### ISSUE TITLE
Can't expand the html description

### ISSUE THREAD

**Issue by ulmi** [NationalSecurityAgency/qgis-kmltools-plugin#1]
Hi,

Right now i'm working on a polygon KMZ/KML that as the `<BR>` tag, and can't expand with the plugin, is the a simple way to add this tag?

The description field has this type of info.

`Unknown Area Type<BR><BR><B>COD_UG</B> = 50242<BR><BR><B>NOME_UNID_</B> = QUEBRADAS<BR><BR><B>COD_TALHAO</B> = T01<BR><BR><B>COD_OCUP</B> = EG<BR><BR><B>PERIODO_RE</B> = 200208<BR><BR><B>CORTE1</B> = 2002<BR><BR><B>CORTE2</B> = 0<BR><BR><B>CORTE3</B> = 0<BR><BR><B>CORTE4</B> = 
0<BR><BR><B>ROTACAO</B> = 2<BR><BR><B>DT_PLANT_I</B> = 198802<BR><BR><B>ANO_FOGO</B> = <BR><BR><B>DIVISAO</B> = 710<BR><BR><B>CONCELHOS</B> = ALFANDEGA DA FE<BR><BR><B>FREGUESIA</B> = ALFANDEGA DA FE<BR><BR><B>HECTARES</B> = 0`

thx in advance

**Comment by hamiltoncj** [comment]
I should be able to hand this type of description data. Look for a new release sometime next week.

**Comment by hamiltoncj** [comment]
@ulmi I just uploaded a new release, version 3.0.1. It is now in the QGIS plugin repo. It works for the sample you gave me. You will need to select that you want to expand tag=value pairs. Let me know how it works and whether there is anything else that you would suggest.

**Comment by ulmi** [comment]
@hamiltoncj 

Sorry only tested it now. Thanks for your time and work, unfortunately it doesn't work.

 I'm sending you some examples u can grab at [this link](https://send.firefox.com/download/5211e5c40a/#vSnkGxg3bHeo6krHFvtDfw)

The plugin is very useful and I manage to get it to work with one of the examples, when I changed the tags to `<td><tr>` in a text editor.

**Comment by hamiltoncj** [comment]
@ulmi 
I was out for a few days so I am just taking a look. Your link for examples has expired or does not work. Could you send it to me again?

When you ran the algorithm did you change "How to expand description field" to "Expand to "tag=value" pairs"?

**Comment by ulmi** [comment]
@hamiltoncj yeah firefox send only works for 24 hours, sorry!!
I'm attaching the [examples.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/2505838/examples.zip) on github

> When you ran the algorithm did you change "How to expand description field" to "Expand to "tag=value" pairs"?

Yes I tried with different results with the examples:
- With example 1 no fields are collected for the html field selection dialog
- With example 2 this error occurs

> File "/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/htmlExpansionDialog.py", line 202, in processAlgorithm
self.htmlProcessor.autoGenerateFileds()
File "/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/htmlExpansionDialog.py", line 66, in autoGenerateFileds
self.htmlparser.processHtmlTagValue(desc)
File "/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/htmlExpansionDialog.py", line 356, in processHtmlTagValue
tag = m[1].strip()
TypeError: '_sre.SRE_Match' object is not subscriptable

thx again for your time and work

**Comment by hamiltoncj** [comment]
@ulmi 
With example 1, it uses a ':' to separate the tag and value. I am looking for an '=' sign.  I can add this.

For example 2 I have not been able to replicate the error. It works for me. What version of QGIS are you using and what operating system are you on? If you are not using the latest QGIS 3 please try updating it and see if you get the same error.

Actually looking at the error message I think I know what is wrong. Look for an update soon.

**Comment by hamiltoncj** [comment]
@ulmi 
In version 3.0.2 I added "tag: value" support; however, your example 1 is really strange. The description field of each Placemark has the tag and values all reversed and cannot be parsed. For the popup in Google Earth it uses Balloon styling text which is in the right order. For me to support the text from styling is going to be a much more difficult task. I don't know why the Placemark description data is so badly formatted that it is unusable.

I think I have fixed example 2. Let me know if it works for you.

**Comment by ulmi** [comment]
@hamiltoncj 
example 2 works flawlessly ;)

The example 1 is a really pain...although the plugin stills helps...a lot, after some "hack n' slash" of the kml on a text editor removing all the styling and converting the tags to a table format with some find & replaces, I managed to expand the description field with the plugin.

It's crud, rudimentary and painfull, but it works.

Thank you again for your work.
