### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by kobusburger** [NationalSecurityAgency/qgis-kmltools-plugin#12]
I am trying to export a vector layer. The layer has rule-based symbology and calculated fields.

QGIS version: 3.18.3-Zürich
QGIS code revision: 735cc85be9
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 1, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['fid','name'], 'ExportStyle' : True, 'InputLayer' : 'C:/Users/kobus.burger/OneDrive - Zutari/KBProjects/SKA MK+/Design/QGIS/MK+.gpkg|layername=CoreMH', 'LineWidthFactor' : 2, 'NameField' : 'name', 'OutputKmz' : 'TEMPORARY_OUTPUT', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

No features processed
Execution completed in 0.18 seconds
Results:
{}

Loading resulting layers
Algorithm 'Export KMZ' finished
QGIS version: 3.18.3-Zürich
QGIS code revision: 735cc85be9
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 1, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['fid','length','name','to','label','area'], 'ExportStyle' : True, 'InputLayer' : 'C:/Users/kobus.burger/OneDrive - Zutari/KBProjects/SKA MK+/Design/QGIS/MK+.gpkg|layername=Williston outer repeater fibre cable', 'LineWidthFactor' : 2, 'NameField' : 'name', 'OutputKmz' : 'TEMPORARY_OUTPUT', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

Only single, categorized, and graduated symbol styles can be exported. Processing will continue without symbol style export.
Traceback (most recent call last):
File "C:/Users/kobus.burger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 461, in processAlgorithm
self.exportName(kml_item, feature[name_field])
File "C:/Users/kobus.burger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 751, in exportName
name = name.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

Execution failed after 0.17 seconds

Loading resulting layers
Algorithm 'Export KMZ' finished

**Comment by hamiltoncj** [comment]
QGIS symbology is much more advance than KML so it is limited what can be supported. I can only support simple, categorized, and graduated symbology, but I don't like seeing an exception generated. I will look into that.

**Comment by hamiltoncj** [comment]
@kobusburger Sorry I accidentally closed the ticket. I just released KML Tools version 3.1.12. It should fix the error you are seeing.

I know of no way to support rule based symbology and have it exported to a KMZ. The only symbology support that can somewhat be replicated in Google Earth is simple, categorized and graduated. I wish I could support them all, but it is just not feasible because KML does not support it.

This fix should at least export your data and it will be displayed with the default symbols in Google Earth. Please test it to make sure and let me know the results.

**Comment by kobusburger** [comment]
Thanks. I did not get the error again. Thank you for an excellent plugin
