### ISSUE TITLE
Geodatabase feature class export failure

### ISSUE THREAD

**Issue by snow-raven** [NationalSecurityAgency/qgis-kmltools-plugin#13]
I'm not sure if this is a bug or an unsupported feature, but I thought I'd let you know. I was unable to export this GDB feature class. Let me know if you want a data sample for testing, as I'm not sure whether it was an issue with this particular file. I was successful after I exported an intermediate shapefile & tried with that, instead.

'---------------------------------------------Failed attempt from Geodatabase----------------------------------------------------------
QGIS version: 3.22.1-Białowieża
QGIS code revision: 663dcf8fb9
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-01-25T09:41:56
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 1, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['OBJECTID','NWI_Code','NWI_Description','HGM_Description','Area_Acres','Reestablishment','Rehabilitation','HGM_Code','SHAPE_Length','SHAPE_Area'], 'ExportStyle' : True, 'InputLayer' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Geodatabase.gdb|layername=Wetlands_Shapefile', 'LineWidthFactor' : 2, 'NameField' : 'NWI_Code', 'OutputKmz' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Geodatabase.kmz', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

Traceback (most recent call last):
File "C:\Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\User/python/plugins\kmltools\exportKmz.py", line 449, in processAlgorithm
kmlpart.outerboundaryis = [(pt.x(), pt.y(), altitude + altitude_addend) for pt in ext_ring]
TypeError: 'QgsCompoundCurve' object is not iterable

Execution failed after 3.69 seconds

Loading resulting layers
Algorithm 'Export KMZ' finished

'---------------------------------------------Failed attempt from Geodatabase with no altitude----------------------------------------------------------
QGIS version: 3.22.1-Białowieża
QGIS code revision: 663dcf8fb9
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-01-25T09:44:19
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 0, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['OBJECTID','NWI_Code','NWI_Description','HGM_Description','Area_Acres','Reestablishment','Rehabilitation','HGM_Code','SHAPE_Length','SHAPE_Area'], 'ExportStyle' : True, 'InputLayer' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Geodatabase.gdb|layername=Wetlands_Shapefile', 'LineWidthFactor' : 2, 'NameField' : 'NWI_Code', 'OutputKmz' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Geodatabase.kmz', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

Traceback (most recent call last):
File "C:\Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\User/python/plugins\kmltools\exportKmz.py", line 449, in processAlgorithm
kmlpart.outerboundaryis = [(pt.x(), pt.y(), altitude + altitude_addend) for pt in ext_ring]
TypeError: 'QgsCompoundCurve' object is not iterable

Execution failed after 3.09 seconds

Loading resulting layers
Algorithm 'Export KMZ' finished

'---------------------------------------------Successful attempt from Shapefile----------------------------------------------------------
QGIS version: 3.22.1-Białowieża
QGIS code revision: 663dcf8fb9
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-01-25T10:00:39
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 0, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['OBJECTID','NWI_Code','NWI_Descri','HGM_Descri','Area_Acres','Reestablis','Rehabilita','HGM_Code','SHAPE_Leng','SHAPE_Area'], 'ExportStyle' : True, 'InputLayer' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Wetlands_Shapefile.shp', 'LineWidthFactor' : 2, 'NameField' : 'NWI_Code', 'OutputKmz' : 'J:/2019/Project Folder/04. Environment/04. Wetlands/GIS/shapefiles/Wetlands_Shapefile.kmz', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

Execution completed in 0.54 seconds
Results:
{}

Loading resulting layers
Algorithm 'Export KMZ' finished

**Comment by hamiltoncj** [comment]
@snow-raven 
Thank you for reporting this. It appears that your original data uses curved geometries which I have not encountered before. I don't think Shapefiles support curved geometry so that is why it worked. I would very much appreciate a sample of the data to see if there is a way to fix this.

**Comment by snow-raven** [comment]
Can do. Can I email you a download link? The file is work-related, so I would need client permission to share it publicly. I can send it directly to you for troubleshooting purposes, however.

**Comment by hamiltoncj** [comment]
@snow-raven
Send me the link to adenaculture@gmail.com. I won't share the data.

**Comment by hamiltoncj** [comment]
@snow-raven I believe this is now fixed. Please let me know if you encounter any other problems.

**Comment by snow-raven** [comment]
Wow, thanks for the speedy fix! Will let you know if I encounter any other problems.
