### ISSUE TITLE
'NoneType' object has no attribute 'style'

### ISSUE THREAD

**Issue by kobusburger** [NationalSecurityAgency/qgis-kmltools-plugin#14]
I was trying the export a layer to kml but it failed. The log is as follows:

QGIS version: 3.24.1-Tisler
QGIS code revision: 5709b82461
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.2
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 1c17a7)
Algorithm started at: 2022-04-06T12:18:35
Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeAddend' : 0, 'AltitudeField' : '', 'AltitudeInterpretation' : 1, 'AltitudeMode' : 0, 'AltitudeModeField' : '', 'DateBeginField' : '', 'DateEndField' : '', 'DateStampField' : '', 'DateTimeBeginField' : '', 'DateTimeEndField' : '', 'DateTimeStampField' : '', 'DescriptionField' : ['fid','Area','Length','Name','To','Label'], 'ExportStyle' : True, 'InputLayer' : 'C:/Users/kobus.burger/OneDrive - Zutari/KBProjects/SKA MK+/Design/QGIS/MK+.gpkg|layername=MK+ Fibre cable', 'LineWidthFactor' : 2, 'NameField' : 'Name', 'OutputKmz' : 'C:/Users/kobus.burger/Downloads/tt.kmz', 'PhotoField' : '', 'TimeBeginField' : '', 'TimeEndField' : '', 'TimeStampField' : '', 'UseGoogleIcon' : None }

Traceback (most recent call last):
File "C:\Users/kobus.burger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 467, in processAlgorithm
self.exportStyle(kml_item, feature, export_style, geomtype)
File "C:\Users/kobus.burger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 538, in exportStyle
kml_item.style = self.cat_styles[catindex]
AttributeError: 'NoneType' object has no attribute 'style'

Execution failed after 0.13 seconds

Loading resulting layers
Algorithm 'Export KMZ' finished

**Comment by hamiltoncj** [comment]
@kobusburger Thank you for reporting this. It is always helpful to have a data sample to replicate the issue. In the meantime I will try to see if I can come up with a reason this is not working, but if there is anything you can share it would make it a lot easier.

Just examining the code I could really use your input data for testing. I am already checking for None and am not sure why this would be occurring. I suspect there is some problem with the geometry of one or more of your layer's features, but KML Tools needs to be robust and handle these cases appropriately.

**Comment by kobusburger** [comment]
Hi

Attached please find a test project and layer that gives the error.

Regards and thank you for a nice plugin

Kobus Burger
+27 83 228 9674

**Comment by hamiltoncj** [comment]
@kobusburger To attach a project you need to go to this issue in github and physically attach it. Sending a response by email does not work. If it is small enough you can email it to adenaculture@gmail.com or if it is larger just put it on google drive or dropbox and send me the link.

**Comment by hamiltoncj** [comment]
I believe this is now fixed as of version 3.1.17. Thanks for reporting the problem and providing test files.

**Comment by hamiltoncj** [comment]
I am closing this issue as it appears to be solved.
