### ISSUE TITLE
KMZ export does not include point styles when selected features is toggled

### ISSUE THREAD

**Issue by jnbroa** [NationalSecurityAgency/qgis-kmltools-plugin#15]
Layer styles do not export when the selected features option is toggled, so that point symbols become the generic thumb tack symbol in Google Earth.

It does not work with the "export style for single, categorized, graduated symbols" option checked nor when a symbol style is selected from the Point Layers drop down. (I tested circles)

Other than that the plugin works great. 

![image](https://user-images.githubusercontent.com/103767644/163595901-cdab1118-f9c3-48de-a046-63bf49d84000.png)

**Comment by hamiltoncj** [comment]
Thanks for reporting this. Unfortunately it may be several weeks before I will be able to fix the problem. I will let you know when it is fixed.

**Comment by jnbroa** [comment]
No worries and I appreciate it.

**Comment by hamiltoncj** [comment]
Thank you for your patience. I was out of the office for a few weeks. I think I have solved this problem and released version 3.1.18. I have found another issue that I need to fix, but decided to release this version and then work on the next problem.

**Comment by jnbroa** [comment]
No problem at all. Thank you for the update and for creating this helpful plugin.
