### ISSUE TITLE
Categoryzed Simbology not exported properly

### ISSUE THREAD

**Issue by Scintsz** [NationalSecurityAgency/qgis-kmltools-plugin#16]
In this latest version (3.1.18), using categoryzed simbology, results in only one of the classifications beeing represented in all vectors. Does anyone else have seen this behavior?

**Comment by hamiltoncj** [comment]
Can you be more specific? The tool was just updated to fix a problem with processing only selected features for points. There is also an issue with polygons that is currently being worked on. Is the problem with points, lines, or polygons?

**Comment by hamiltoncj** [comment]
I released KML Tools 3.1.19. There are several bugs that I fixed. I hope one of them is the one you are talking about. If not let me know.
