### ISSUE TITLE
Cannot set KMZ Vector NameField without also exporting a placemark?

### ISSUE THREAD

**Issue by timbo-barnes** [NationalSecurityAgency/qgis-kmltools-plugin#17]
Previous behavior of the KMZ Export tool that you could set the NameField value so that each polygon in the KMZ had a 'title' in the legend.
Now when setting the NameField, each polygon does have a 'title' in the legend but also has a placemark/label point in Google Earth- This can cause slow loading and instability for files with lots of polygons/labels
Can this be changed back or another option added to export/not export the placemark/label point?

**Comment by hamiltoncj** [comment]
I made that change due to a request by another user. I will make that behavior optional.

**Comment by hamiltoncj** [comment]
@timbo-barnes I released KML Tools 3.1.21 and have made the hidden point used for polygon labels optional. There is a new check box for this.

**Comment by timbo-barnes** [comment]
Thanks so much for the fast response!
