### ISSUE TITLE
Missing QgsProcessingException import in importKml.py

### ISSUE THREAD

**Issue by mdsandell** [NationalSecurityAgency/qgis-kmltools-plugin#2]
When (accidentally) trying to import a .kml file that isn't actually KML data, the import errors because QgsProcessingException is undefined. Granted, this would still error either way, but it's not the _intended_ error. It looks like it's simply missing a python import statement near the beginning of importKml.py.

```
Invalid extension: Should be kml or kmz
Failed to open file
Traceback (most recent call last):
File "/Users/Mark/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kmltools/importKml.py", line 84, in processAlgorithm
raise QgsProcessingException(msg)
NameError: name 'QgsProcessingException' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Mark/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kmltools/importKml.py", line 88, in processAlgorithm
raise QgsProcessingException(msg)
NameError: name 'QgsProcessingException' is not defined

Execution failed after 0.03 seconds
```

**Comment by hamiltoncj** [comment]
Thanks for letting me know about that bug. I just pushed out a new version with the exception fixed.

**Comment by hamiltoncj** [comment]
I believe this has been fixed, but if you find another problem please let me know.

Thanks!
