### ISSUE TITLE
Add `Extend sides to ground` option to KMZ Export for Google Earth

### ISSUE THREAD

**Issue by vincentvdwal** [NationalSecurityAgency/qgis-kmltools-plugin#20]
When exporting using `KMZ Export` I am missing an optional flag to extend the sides to ground. 
Currently the Altitude and Altitude modes are working really well. Just annoying you have to add a checkmark in Google Earth manually.
Could this be added?

**Comment by hamiltoncj** [comment]
I can add that in. I should have it done by the end of next week.

**Comment by hamiltoncj** [comment]
I had some time this afternoon and added a checkbox to extend sides to the ground. This is in version 3.1.23. You will need to make sure the right altitude mode is selected as well. Let me know if this works as you expect it to.

**Comment by vincentvdwal** [comment]
Works perfectly, thanks!
