### ISSUE TITLE
Incorrect symbol encoding

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#22]
Hi,
I would like to ask if this type of symbol can be correctly displayed at the marker title. As you can see, in the descriptions the symbol is correct.
![image](https://user-images.githubusercontent.com/29894272/204049805-672ce52c-f933-4df1-af84-5acdd65f0eb0.png)
Thanks again for your help and attention.
Nelson Muylaert

**Comment by hamiltoncj** [comment]
I will take a look at it. This is one of problems with KML in that is using HTML formatting, but QGIS labeling does not. There should be some library function that turns this back into text.

**Comment by hamiltoncj** [comment]
I found a problem with the way I had implemented this. I just released version 3.1.26 which should fix this issue. Let me know how it goes.

**Comment by Bunanai** [comment]
Excellent, it works very fine now.
Congratulations on your commitment and effort to improve the plugin.
And thank you very much for the rapid reply.
Regards.

**Comment by hamiltoncj** [comment]
I'm glad it works. Let me know if you ever encounter any other problems. Happy holidays!
