### ISSUE TITLE
Line feed character export

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#23]
Hi, it´s me again. I would like to know if it is possible to include the Line Feed (LF) character (/n) in kmz exported file. 
The motivation is that some Qgis field has too much information, so I use the LF to try to organize a little bit the information in separate lines (see attached image).

![image](https://user-images.githubusercontent.com/29894272/208280762-58937c7f-038b-40a8-afcf-e362a5cc8389.png)

But in kmz file, the information appears all lines together with no LF:

![image](https://user-images.githubusercontent.com/29894272/208280810-6eea9857-00f3-4144-994f-d57f7f93b2a3.png)

Is it possible to implement this suggestion?

And I think that is not possible to configure the exportation process to put the information also into the description tab of kmz POI, which at the present moment, has the HTML table string:

![image](https://user-images.githubusercontent.com/29894272/208280901-d0a7bd9f-aa53-4bed-8b54-adc69a82380a.png)

Thank you again for your attention and dedication to supporting and improving this wonderful plugin.

Nelson Freitas.

**Comment by hamiltoncj** [comment]
Currently if only one description field is specified then it does not use the HTML formatting. There are several possibilities. 1) CR/LFs could be interpreted as an HTML <BR> tag. 2) There could be another mode of operation where it doesn't use HTML syntax, but simply adds it as text in a "tag: value LF" order. Do you have a small sample of data that you can export as a GPKG and zip it up so I can look at it as it is in QGIS? Note: Tomorrow is my last day at work until January so it may take a while to look at this.

**Comment by Bunanai** [comment]
There is the zip example. 
I´m opening a lot of kmz/kml exported files in visual studio in order to discover some differences between them. Also reading the XML standards to improve my understanding of the terms used.
[test CRLF.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10272051/test.CRLF.zip)

**Comment by hamiltoncj** [comment]
I added a parameter in the Advanced tab to add line breaks in the description. I have it checked by default so you don't have to do anything. Test the attached plugin to see if it does what you want. Uninstall your existing KML Tools, and then use the Install from ZIP to install this one. Also test it with android devices to see if it works. There is one change that might make a difference.
[kmltools_test.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10278444/kmltools_test.zip)

**Comment by Bunanai** [comment]
Perfect!!!!! It works as I wanted also with Andriod and PC versions. I hope your dedication can help many other people in the GIS community. Considering you found a way to solve it, can this option be applied to the label too? 
I would like to contact you directly to thank all these implementations you´re doing. Is it possible?

**Comment by hamiltoncj** [comment]
I will take a look at the label. My email is a part of the plugin contact information.

**Comment by hamiltoncj** [comment]
I came down with the flu so it will be next week before I can look at this.

Incidentally, I cannot accept donations for my work.

**Comment by hamiltoncj** [comment]
I looked into a multiple line label and it appears that KML standard does not allow it. There can only be one line.

**Comment by hamiltoncj** [comment]
@Bunanai The plugin you tested was added as 3.1.27 in the plugin repo. Multiple line labels are not possible. Can this ticket be closed?

**Comment by hamiltoncj** [comment]
I think this one is solved so I am going to close it.
