### ISSUE TITLE
Android Google Earth crashes

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#24]
Hi.

I´m getting crashed on google earth on various android mobiles when opening a kmz exported by the plugin. It´s curious that some files always crash, and others I need to follow a given pattern of process to use. On the desktop google earth all runs ok. 
When opening a kmz file, if I select directly a placemarker on the map (A), it crashes. If I choose the item on the project folders first (B), everything goes right.

![image](https://user-images.githubusercontent.com/29894272/208480799-9f2909e0-558a-4799-9b40-37771b752d85.png)

Sorry, but I don´t have much experience to help with the problem, but I´m ready for everything you need.

I posted an example file in other to make some tests.

Regards.

Nelson Muylaert

[teste KT.kmz.txt](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10261547/teste.KT.kmz.txt)

**Comment by hamiltoncj** [comment]
I don't see anything wrong with the KML that is generated. I made one small change with HTML formatting, but it shouldn't make any difference. I am attaching two files. Can you tell if they work or not. The second text file does not create image icons, but uses the Google Earth icons. I have zipped the files together since GitHub does not support attaching .kmz files. Please unzip them first. Let me know the results.
[test_files.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10268925/test_files.zip)

**Comment by hamiltoncj** [comment]
Here is another file to try. Just rename test3.zip to test3.kmz. I removed some of the fancy formatting that references the extended data with something like $[id] and instead put in the text.

[test3.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10269274/test3.zip)

**Comment by Bunanai** [comment]
Great. I´ll try and give you feedback as soon as possible, maybe until tomorrow.

**Comment by Bunanai** [comment]
The same problem... None of these three options run ok. Here´s the google feedback, maybe could help.

![WhatsApp Image 2022-12-29 at 11 18 15](https://user-images.githubusercontent.com/29894272/209966302-285e20cd-072a-4029-b268-a449c6e12bef.jpeg)

**Comment by Bunanai** [comment]
Sincerely I´m very glad and thankful for every implementation you´ve done up to now. Even though it´s a GIS community work and you do it for pleasure or to increase your engagement with the GitHub metrics, I would like to give you a little donation to thank all the helpfulness and time spent on these implementations. It is not so much, It has been helping me very much on my work. 
I don´t know about your occupation, free time, and goals but I´m looking for some GIS and Python guru to guide me through the challenges to get better in these subjects. 
With your permission, we can talk by whatsapp sometimes, I can ask some questions and we can combine a value to this.
If not, no problem, I´m extremely happy with the way it is. 
So, feel free to reply to this number +55 47 9 9629 9779.

**Comment by hamiltoncj** [comment]
@Bunanai You reopened this ticket. Is there still a problem?

**Comment by Bunanai** [comment]
I closed it accidentally, my apologies. It´s still crashing.

**Comment by hamiltoncj** [comment]
@Bunanai I giving you two more files to try. They both have a .zip extension. Don't unzip them just rename them test5.kmz and test6.kmz. text6 has the ExtendedData tag removed. Both are generated from the latest KML Tools. If one or both of these don't work then I have no idea what may be the problem.
[test5.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10414759/test5.zip)
[test6.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10414760/test6.zip)

**Comment by hamiltoncj** [comment]
@Bunanai Were you able to test the latest two files?

**Comment by Bunanai** [comment]
As I´m not having so much time to make a deep test on it and considering that can have some relation with google earth mobile itself, I suggest closing this issue and if necessary, I open another with more details. Thanks again for the support.

**Comment by hamiltoncj** [comment]
Okay and thanks for all your suggestions and helping to improve the plugin.
