### ISSUE TITLE
KMLTools exportkmz in PyQGIS crashes the QGIS application

### ISSUE THREAD

**Issue by vincentvdwal** [NationalSecurityAgency/qgis-kmltools-plugin#25]
Running the code below works. But immediately after execution QGIS crashes and closes. I tried all options and flags, which don't seem have to have any effect on the script crashing. Would be cool if this could be fixed, for automation purposes.

```python
processing.run("kmltools:exportkmz", {
        "InputLayer":kmzInputPath,
        "OutputKmz":kmzOutputPath,
        "SelectedFeaturesOnly":False,
        "NameField":"XXX",
        "HiddenPolygonPointLabel":False,
        "DescriptionField":[
            "XXX",
            "XXX"
        ],
        "ExportStyle":True,
        "UseGoogleIcon":None,
        "AltitudeInterpretation":1,
        "AltitudeMode":1,
        "AltitudeModeField":"",
        "AltitudeField":"Altitude",
        "AltitudeAddend":0,
        "ExtendSidesToGround":True,
        "DateTimeStampField":"",
        "DateTimeBeginField":"",
        "DateTimeEndField":"",
        "PhotoField":"",
        "LineWidthFactor":2,
        "DateStampField":"",
        "TimeStampField":"",
        "DateBeginField":"",
        "TimeBeginField":"",
        "DateEndField":"",
        "TimeEndField":""
})
```

**Comment by hamiltoncj** [comment]
What operating system are you on? If it is Ubuntu, there is a good chance that it is not KML Tools, but the version of PROJ you are using.

**Comment by hamiltoncj** [comment]
@vincvdwal Did you have any more information about this?

**Comment by vincentvdwal** [comment]
Sorry, missed your first comment. 

Yes, although I work on a Linux distribution, I've tested it on a Windows system, and there it also crashed in the same way. Personally, I don't think it has to do with the PROJ version.

**Comment by hamiltoncj** [comment]
@vincvdwal I really need the error message or a test data set with a description on how to replicate the problem.

**Comment by hamiltoncj** [comment]
@vincvdwal I tried running this is the Python console using a natural earth port shapefile. It didn't cause any crashing. Did you 'import processing" before trying this? Here is my code.
processing.run('kmltools:exportkmz', {
        'AltitudeAddend': 0,
        'AltitudeField': 'altitude',
        'AltitudeInterpretation': 1, 
        'AltitudeMode': 1, 
        'AltitudeModeField': '',
        'DateBeginField': '',
        'DateEndField': '',
        'DateStampField': '',
        'DateTimeBeginField': '',
        'DateTimeEndField': '',
        'DateTimeStampField': '',
        'DescriptionField': ['name','name'],
        'ExportStyle': True,
        'ExtendSidesToGround': True,
        'HiddenPolygonPointLabel': False,
        'InputLayer': 'W:/My Documents/Data/10m_cultural/ne_10m_ports.shp',
        'LineWidthFactor': 2,
        'NameField': 'name',
        'PhotoField': '',
        'SelectedFeaturesOnly': False,
        'SubFolderField': '',
        'TimeBeginField': '',
        'TimeEndField': '',
        'TimeStampField': '',
        'UseDescBR': True,
        'UseGoogleIcon': None,
        'OutputKmz': 'C:/Users/user/Desktop/test1.kmz'
    })

**Comment by vincentvdwal** [comment]
Sorry it took so long to reply, only had some time to look at it now. 
I replaced all `path strings` with the `pathlib` library and now it runs smooth as butter. Wasn't a problem of your tool after all. Sorry for the inconvenience and thanks again for checking in so quickly! Really like this tool, using it a lot.
