### ISSUE TITLE
Export Alias and hide description field

### ISSUE THREAD

**Issue by Monje96** [NationalSecurityAgency/qgis-kmltools-plugin#26]
Hello. 
Two questions:
1 - Is there a way to export field alias insted of field name from shp to kmz?
2- And is it possible to hide the subtext and keep all table records as in the second image?

![imagen](https://user-images.githubusercontent.com/73607546/221232607-7b53e42a-c8c5-4de2-ac14-7d20b5e9317e.png)

![imagen](https://user-images.githubusercontent.com/73607546/221233428-fea3e6f6-9939-4d87-864a-f3c9d87ce118.png)

Thank you!

**Comment by hamiltoncj** [comment]
Sorry for the slow response. I have been pulled off of QGIS development and can only fix bugs. You can choose any qgis attribute for the label in the kmz and any of the attribute fields to be added to the description area. What the attribute is named in the attribute table is what it will be named in the kmz. I wish I could help more, but if the existing functionality does not meet your needs I cannot do anything about it as my hands are tied.
