### ISSUE TITLE
Import html embedded information

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#31]
Hi, I used the KT to import a KMZ line file with some embedded HTML information (https://drive.google.com/file/d/10P_SEI-laitHBYsF2-fQ50FJTScGP7lj/view?usp=sharing). But none of them were imported to Qgis, as you can note above:

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/890cb0ad-2e74-424a-95be-a9038349a28e)

Did I miss something? If not, is it possible to implement this and what are the implications?
Thank you.

**Comment by hamiltoncj** [comment]
I should be able to fix this. Normally the ExtendedData tag internally uses a "Data" tag for the values, but in this case it is a SimpleData tag which I have not yet seen, but I should be able to add it in.

**Comment by hamiltoncj** [comment]
There is a new version of the plugin that supports the SimpleData tag. (3.1.30)

**Comment by Bunanai** [comment]
I installed the zipped code downloaded from  GIT, since the upgrade isn´t available at QGIS complements yet. But now appears two plugins installed. See below.
![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/42c1b4e6-8e34-4d36-b329-066b9ac4918e)

**Comment by hamiltoncj** [comment]
I'm not sure why you are seeing two. When you launch QGIS it does a query of the plugins database and unless you go into "Plugins->Manage and Install Plugins...", click on the Settings tab, and click on the "Reload all Repositories" button, then you won't see the new updates. You can always quit QGIS and then go back in and you should get the current database of QGIS plugins. If you are still seeing KML Tools twice, I would delete them both and then install the new version.

**Comment by Bunanai** [comment]
Wow you´re brilliant, working like a charm! Thank you very much. The repository issue was solved too. I sincerely wish Qgis project could count on your full support soon.
