### ISSUE TITLE
Error range object message - graduated symbology

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#33]
(Qgis 3.28.9  Plugin: 3.1.30 SO: Win 10)

Hi,
I´m getting a list of this error when exporting a graduated symbology layer:

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/db9acd4c-f26a-44ad-84c7-5e33b2bee19c)

I don´t know but only the selected legend features (A) appear with the circle marker (which I have chosen) on KMZ (B), the others come with the GE default pin image. 

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/a7acdc43-4a6c-49c1-a942-96b659d88721)

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/da2e7745-06d2-4785-be41-a89c61fdcb46)
 
This is the symbology configuration:

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/36d0cc81-cbc6-4b2b-824c-797a647e8c79)

And this is part of plugin configuration:

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/29894272/55a6c7bc-179d-4128-9deb-1b0944292334)

Do you have any idea of what is happening?

**Comment by hamiltoncj** [comment]
Unfortunately, I have not been able to reproduce the error. I tried using a subset of the Natural Earth Airport data that had a field that I could categorize. I matched my input parameters (with the exceptions that it is not your date) to that of yours as close as I could. Everything I tried worked. How big is your data set? If you can somehow isolate the problem with a small data set that you can share and give the instructions on how it could be reproduced, then I could take a look. If you have a really large data set with limited memory, it may be running into some resource limitations.

**Comment by Bunanai** [comment]
Ok, I´ll give a full dataset parameters and data to go foward with your test.
Here is:
https://1drv.ms/u/s!AqZP8TBQO3VJj_AzqZBbo1Z1nW1SVQ?e=nvDxK6
Json file is the plugin batch configuration. Some fields you need to fix to   your reality.

**Comment by hamiltoncj** [comment]
I did not notice that you had some of the classes unchecked so I now see the problem. I will let you know when I come up with a solution. Thanks for the data and notifying me of this issue.

**Comment by hamiltoncj** [comment]
This turned out to be a misunderstanding with style gradients/categories and the ability to filter the date simply by turning a style on or off. I have released version 3.1.31. You may need to restart QGIS to get an updated plugin list. Let me know if you have any further problems.

**Comment by hamiltoncj** [comment]
I believe this is solved with the latest release so I am closing the ticket.
