### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by dmburgess** [NationalSecurityAgency/qgis-kmltools-plugin#34]
getting error code 1 but do not see what that error code is.

**Comment by dmburgess** [comment]
----------------
Inputs
----------------

GroundOverlayFolder:    '788828_7.gtif'
Input:  C788828_7.kml
LoadGeoTiffs:   true

Using ellipsoid:        EPSG:7030
Using distance unit:    meters
Using area unit:        square meters

Process returned error code 1

----------------
Results
----------------

**Comment by hamiltoncj** [comment]
How are you running this? Can you post the log output that you would see from running it in QGIS or can you share your kmz file? I don't know where you would see messages that says it returned an error code 1.

**Comment by dmburgess** [comment]
Command line.

**Comment by hamiltoncj** [comment]
I was wondering if that was the case. It is meant to be run within QGIS. I've never tried running it from the command line, but having LoadGeoTiffs as true will definitely not work because it is expecting to be interacting with the QGIS interface. Try it will false.

**Comment by dmburgess** [comment]
We did finally get it to work.  So far so good.  The geotiff is loaded, we need to convert it to vector as well, that takes a bit of time using gdal_polygonize..
