### ISSUE TITLE
AttributeError: 'QgsGeometryGeneratorSymbolLayer' object has no attribute 'strokeStyle'

### ISSUE THREAD

**Issue by martin-laurent** [NationalSecurityAgency/qgis-kmltools-plugin#35]
When trying to export a polygon layer, the following error is raised:
`AttributeError: 'QgsGeometryGeneratorSymbolLayer' object has no attribute 'strokeStyle'`

The traceback points to:
```
kmltools/exportKmz.py, line 847, in initStyles
    stroke_style = symbol_layer.strokeStyle()
```

which sounds like this statement is using a deprecated method `strokeStyle`. It's unclear if there is a previous version of QGIS where this would work, but in any case, exporting polygons doesn't seem to work anymore.

I'm using these versions:
```
kmltools | 3.1.31
QGIS version | 3.32.2-Lima
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
OS version | macOS 13.5
```

**Comment by hamiltoncj** [comment]
Thanks for letting me know. The QGIS style API has been problematic because they keep updating it without notice or without any notice that I see. I will check into it to see if was an API change or some other problem.

**Comment by hamiltoncj** [comment]
@martin-laurent Hi Martin, Could you give me more details on the data set you are using and if possible a small sample of the polygons that are causing a problem. I have not been able to replicate your error. I have tried several different polygon layers. All have worked. From the point in the code it indicates that you are using a graduated style. I have tested it with this and it worked. I am testing it this morning with the latest 3.34 release of QGIS. Is it possible you have some bad geometries in your data? If you have some sample data that would really help. If you do have some sample data let me also know how you style it.

**Comment by hamiltoncj** [comment]
@martin-laurent I checked strokeStyle in the documentation and it is NOT deprecated so something else is the problem.

**Comment by hamiltoncj** [comment]
@martin-laurent Do you have any more information on this; otherwise, I will go ahead and close it.

**Comment by hamiltoncj** [comment]
Closing because of lack of receiving more information.
