### ISSUE TITLE
Error exporting polygon layer: no attribute 'strokeStyle'

### ISSUE THREAD

**Issue by EricUniqueUsername** [NationalSecurityAgency/qgis-kmltools-plugin#37]
Hello-
I don't know if this warrants a bug report, but I wanted to signal this error. I'm very new to QGIS and have next to zero Python skill.
I was running a batch conversion with one point file and one polygon file. The point file was successful, but the polygon was not. But I can't understand the error log well enough to troubleshoot. It seems to indicate some problem with the symbology of the polygon layer, which is shown in the attached screenshot.
![grant_polygon_symbology_QGIS](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/61940118/01dc55ac-7050-46d5-9dbd-697fe40d0c55)

Thanks for providing this tool, and thanks in advance for any help. Apologies if this post is not in order.
[Export KMZ polygon error - no strokeStyle.txt](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/14968412/Export.KMZ.polygon.error.-.no.strokeStyle.txt)

Adding side note: When I tried exporting the polygon layer with another plugin, Layer2KMZ, it failed with this apparently related error: "Error: 'QgsSimpleLineSymbolLayer' object has no attribute 'strokeWidth'"

Further note:
The conversion worked when I unchecked the "export style..." option.
Eric

**Comment by hamiltoncj** [comment]
I was able to replicate the problem. I will see if I can fix it.

**Comment by hamiltoncj** [comment]
I added support for the simple outline for polygons. It is release 3.1.33. KML is very limited with the type of styling that can be done so advanced QGIS styling cannot be exported.

**Comment by hamiltoncj** [comment]
Did this fix solve the problem you were having?

**Comment by EricUniqueUsername** [comment]
Hi CJ- Yes, I just saw the plugin update, installed it, and recreated the same operation with no trouble.
Thanks!
Eric
