### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ozhamlet** [NationalSecurityAgency/qgis-kmltools-plugin#4]
An additional useful feature for the export module when exporting polygons would be to have the option to add a label at the centroid using the MultiGeometry tag along the lines suggested here:
https://support.google.com/earth/forum/AAAA_9IoRZwUMW8DH3SWK0/?hl=en&gpf=%23!topic%2Fearth%2FUMW8DH3SWK0

**Comment by hamiltoncj** [comment]
@ozhamlet That is an excellent suggestion. I should have some time to work on it in the next few weeks.

**Comment by hamiltoncj** [comment]
@ozhamlet I just put out a new release, 3.1.3, that implements your suggestion. Let me know how it works out for you.

**Comment by ozhamlet** [comment]
@hamiltoncj that worked, thanks for the quick implementation.  The icing on the cake would be an option for just a single label for multi-polygon objects; e.g. localities with off-shore islands:
![image](https://user-images.githubusercontent.com/38339889/105616931-6bbffb00-5e15-11eb-878a-348b3b933ca1.png)

**Comment by hamiltoncj** [comment]
@ozhamlet It actually only creates one label for a QGIS multi polygon. I just tested it. If you are seeing multiple labels for each island then they are not multi-polygons in QGIS. You would need to group them together first before exporting as a KMZ.

I am going to close this ticket, but if you have any other suggestions please let me know.
