### ISSUE TITLE
Symbology export for graduated points

### ISSUE THREAD

**Issue by talledodiego** [NationalSecurityAgency/qgis-kmltools-plugin#5]
Is it possible to extend the plugin export the symbology of points set as graduated? Or are there any technical issues that make it impossible?

**Comment by hamiltoncj** [comment]
@talledodiego It should be possible to implement, but does introduce some challenges. QGIS graduated symbology is algorithmic, but you cannot do that in KMLs. What could potentially happen is that for every feature in the exported QGIS data, a style for each feature would need to be created and for point features I export it as PNG images so for 10,000 features I might need to include 10,000 images in the KMZ. Most of the time this probably wouldn't happen, but it could. I am considering first looking at the number of unique styles and if it exceeds a certain number, warning the user and they would then need to override the default number before it would process.

How useful do you think graduated symbology would be to have implemented?

**Comment by talledodiego** [comment]
It can be very useful in cases where no categorization is even possible.
For instance I'm exporting points that are colored from interferometric SAR analysis.

I understand your point and could be actually be a problem unless we could sub-sample the categorization and so defining 9-10 (or n) colors and every feature within the range takes its color class.

Another possibility could be an in-between solution?

Instead of creating a png with the symbology one could use one of the symbols already provided by Google Earth and just assign the color taken from the feature.

```
<Style id="style1">
    <IconStyle>
        <color>ff0000ff</color>
        <scale>1.0</scale>
        <Icon>
            <href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
        </Icon>
    </IconStyle>
</Style>
```

In this code for instance the color (that could be any color) is applied to the png provided by google and you could just write the code for the definition of the color.

Can be a solution?

Eventually I can try to help with that.

**Comment by hamiltoncj** [comment]
Those are great suggestions. I will look into it more and see what I can come up with.

**Comment by hamiltoncj** [comment]
As an update, I should have this working sometime next week. I just about have it completed, but need to do some more testing.

**Comment by talledodiego** [comment]
Cool! 
What approach did you decide to follow?

**Comment by hamiltoncj** [comment]
I didn't really understand graduated symbology until I took a look at it, and it is really no different from categorized. I have put out a new release 3.1.4 that has this capability. I also added the ability to use a small set of Google Earth symbols, but with QGIS color and size. Let me know if the update works for you.

**Comment by talledodiego** [comment]
It works well!
Actually both categorized and graduated don't work when a formula is given in QGis for categorizing/graduating. I mean you are allowed in QGis to graduate based on "myField*10", but it does not work with this plugin.
I think it is because the plugin does not have the parser of Qgis. I am wondering if there is a way to ask QGis to give the color of the entity, without computing it in the plugin.

Despite that problem, defining a new "virtualField = myField*10" and using "virtualField" in the plugin everything works fine.

**Comment by hamiltoncj** [comment]
The plugin can only work with simply solid colors and line widths. I don't know if it is easily possible to extract the color from an expression in the QGIS API. It is something to investigate. Advanced QGIS styling just cannot be translated into Google Earth styling.

**Comment by hamiltoncj** [comment]
I see the problem you mention with an expression and will look to see if there is a method to solve it.

**Comment by hamiltoncj** [comment]
@talledodiego I have updated KML Tools to version 3.1.5. It now supports expressions for the value in categorized and graduated styling. Let me know if this works for you.

Thanks!

**Comment by talledodiego** [comment]
I got this error:
```
Traceback (most recent call last):
File "C:/Users/dtalledo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 420, in processAlgorithm
self.exportStyle(kml_item, feature, export_style, geomtype)
File "C:/Users/dtalledo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kmltools\exportKmz.py", line 494, in exportStyle
symbol = range.symbol()
AttributeError: 'NoneType' object has no attribute 'symbol'

Esecuzione fallita dopo 31.77 secondi
```

The attribute symbology was coloured by means of the simple expression: "Vel x 10" where Vel is an attribute of the layer.
Removing Vel*10 and leaving only Vel, the script works correctly. I will dig better on the data to exclude some errors on it.

**Comment by talledodiego** [comment]
Ok, I got the problem.
The problem is because a certain value is outside the range. 
Why this happend? And could it happen potentially often? I think yes, because when the user defines its own symbology defining manually the classes for the colors to have nice ranges one could copy-paste the symbology to other layers, potentially generating this kind of error. 
A solution to this would be to clip values between max and min? I just created a PR with this feature implemented together with a new parameter "Altitude Addend"

**Comment by hamiltoncj** [comment]
Thanks for your contributions. Version 3.1.6 was added to the QGIS plugin repo with these changes.

**Comment by talledodiego** [comment]
Thanks!

**Comment by hamiltoncj** [comment]
I will go ahead and close this request, but if you encounter anything else, please open up a new request.
