### ISSUE TITLE
Add the ability to include images in the info box

### ISSUE THREAD

**Issue by hamiltoncj** [NationalSecurityAgency/qgis-kmltools-plugin#7]
This could be implemented in two ways. 
1) Each QGIS feature would have a field with a local file pointer to an image. These images would be copied into the KMZ and included as part of the popup window.
2) The QGIS KMZ export would specify a folder of images to be included in the KMZ. The user would be responsible to provide html image links in an attribute from the attribute table to be part of the popup description.

I think I favor the second solution, but if anyone looks at these Issues, I welcome how you would like to see this work.

**Comment by talledodiego** [comment]
Can this idea be used to generate diagrams? 
For instance each feature has a time history of recorded deformations, I could generate a diagram with matplotlib and show it on the infobox of Google Earth?

**Comment by hamiltoncj** [comment]
I am not sure what you mean by generate diagrams. The main idea here that someone asked for was to have an additional export parameter that points to a folder of images that would be included in the KMZ. Then in the attribute table there would be a field for the file name. If the file name is there then it will display the image at the top of the Google Earth popup info box so if you generated matplotlib images and saved them into a folder and added the image attribute then yes it would show up.

I don't know if there is a better workflow for this or not. It was an idea that one person had and I didn't know whether I should work on it or not.

**Comment by talledodiego** [comment]
As an example of diagram I mean something like this where there is the time_history of displacements (this is a set of attributes for my features): 
![image](https://user-images.githubusercontent.com/38036285/109304055-f8f2d700-783b-11eb-96c6-7324955c8d88.png)

The workflow seems reasonable, although error prone. This can be frustrating in particular when the file size increases. A possible solution can be to include a flag the user can select that stops the execution of the process if the filename specified in the attribute field is not included in the folder. Makes sense?

**Comment by hamiltoncj** [comment]
@talledodiego Initial release of this capability is in QGIS 3.1.9. If there is a photo path field in the attribute table, then the image will be copied into the KMZ and will be displayed in the popup. Future releases could include the ability to adjust the max-size of the image.
