### ISSUE TITLE
Exporting style of points layer

### ISSUE THREAD

**Issue by bwwjohnson** [NationalSecurityAgency/qgis-kmltools-plugin#9]
Hi I'm trying to export the shapefile _kishlaks_destroyed.shp_ to  the kml file _khait_1949_evans_building_destruction_points.kml_ . I've specified a categorised styling for the layer using the _destructio_ attribute using the Layer Styling panel.  (I had to upload these as text files)

On Export KML I chose:
Name/Label Field:  _destructio_ 
Description Fields: _destructio_
Export style for..... : tick
Point Layers:  circle placemark
Don't use altitude
Clamp to ground
Leave all the other options blank except Line Width Multiplication factor, which is 2.
Then I save the output to a path. 

I get the output below and no kmz/kml file. Can you help? Thanks!

Algorithm 'Export KMZ' starting…
Input parameters:
{ 'AltitudeField' : None, 'AltitudeInterpretation' : 0, 'AltitudeMode' : 0, 'AltitudeModeField' : None, 'DateBeginField' : None, 'DateEndField' : None, 'DateStampField' : None, 'DateTimeBeginField' : None, 'DateTimeEndField' : None, 'DateTimeStampField' : None, 'DescriptionField' : ['destructio'], 'ExportStyle' : True, 'InputLayer' : '/Volumes/A_500gb_ben/phd/GIS/data/fault_traces/khait_mapping/evans_rasters/kishlaks_destroyed.shp', 'LineWidthFactor' : 2, 'NameField' : 'destructio', 'OutputKmz' : '/Volumes/A_500gb_ben/phd/GIS/data/fault_traces/khait_mapping/kmls_for_richard/khait_1949_building_destruction.kmz', 'TimeBeginField' : None, 'TimeEndField' : None, 'TimeStampField' : None, 'UseGoogleIcon' : 1 }

Traceback (most recent call last):
File "/Users/BenJohnson/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kmltools/exportKmz.py", line 415, in processAlgorithm
self.exportStyle(kml_item, feature, export_style, render, geomtype)
File "/Users/BenJohnson/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kmltools/exportKmz.py", line 473, in exportStyle
kml_item.style = self.cat_styles[catindex]
AttributeError: 'NoneType' object has no attribute 'style'

Execution failed after 0.06 seconds

Loading resulting layers
Algorithm 'Export KMZ' finished

[kishlaks_destroyed.shp.txt](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/6011260/kishlaks_destroyed.shp.txt)

[khait_1949_evans_building_destruction_points.kml.txt](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/6011266/khait_1949_evans_building_destruction_points.kml.txt)

**Comment by hamiltoncj** [comment]
Thanks for letting me know and I especially thank you for providing the data. It might be a few days before I get a solution to the problem, but hopefully by the end of next week I will solve it.

**Comment by hamiltoncj** [comment]
As an update, kishlaks_destroyed.shp.txt does not work. There are more files to a shapefile than just one. On another issue I am working on something that might fix this problem as well. Wait for the next update and we will see if it works or not.

**Comment by hamiltoncj** [comment]
@bwwjohnson I just updated KML Tools to version 3.1.5. I have not specifically taken a look at the problem you were experiencing, but I have addressed another problem and I think it will fix this one as well. If it doesn't please let me know and I will work on it next week.

**Comment by hamiltoncj** [comment]
@bwwjohnson I am guessing that with the last changes I have made, this should be fixed. Let me know if it works properly for you, but make sure you update your KML Tools to the latest version which is 3.1.6.  I will close this ticket by next week unless you find there is still a problem.

**Comment by hamiltoncj** [comment]
I am closing this due to lack of feedback. I think the problem is probably resolved with the latest updates. If you still find a problem please open a new ticket.
